package common

import (
	"gopkg.in/yaml.v2"
	"io/ioutil"
)

// generated by https://mengzhuo.github.io/yaml-to-go/
type T struct {
	Port int `yaml:"port"`
	Log  struct {
		Level            string   `yaml:"level"`
		Encoding         string   `yaml:"encoding"`
		OutputPaths      []string `yaml:"outputPaths"`
		ErrorOutputPaths []string `yaml:"errorOutputPaths"`
	} `yaml:"log"`
	Gin struct {
		Logfile string `yaml:"logfile"`
	} `yaml:"gin"`
	Ldap struct{
		BindAddr string `yaml:"bindAddr"`
		BindPort int    `yaml:"bindPort"`
		BindDN   string `yaml:"bindDN"`
		BindPW   string `yaml:"bindPW"`
        BaseDN   string `yaml:"baseDN"`
	} `yaml:"ldap"`
}

var Config T

func init() {
	content, err := ioutil.ReadFile("conf/ldap-api.yaml")
	if err != nil {
		panic("read config file failed")
	}
	err = yaml.Unmarshal(content, &Config)
	if err != nil {
		panic("unmarshal config file failed")
	}
}
